# Generated by Django 5.1.4 on 2024-12-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
